ref: rename to mcpd

diff --git a/samples/basic/echo-json b/samples/basic/echo-json
--- a/samples/basic/echo-json
+++ b/samples/basic/echo-json
@@ -10,7 +10,7 @@ if [ "$1" = "--help" ]; then
   # Second line to stderr: options definition
   # - required: false means this option is optional
   # - default_value: used when option is not provided
-  echo '{"message": {"description": "Message to echo", "required": false, "value_type": "string", "default_value": "Hello from RestCommander!"}}' >&2
+  echo '{"message": {"description": "Message to echo", "required": false, "value_type": "string", "default_value": "Hello from mcpd!"}}' >&2
   exit 0
 fi
 
